version: "3.9"

services:
  nextjs-app:
    image: ghcr.io/${REPO_USER}/agilebang-ui:latest
    container_name: agilebang-ui
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - agile-net

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
    depends_on:
      - nextjs-app
    networks:
      - agile-net

networks:
  agile-net:
    external: true
